drop table if exists "user" cascade;
drop table if exists card cascade;
drop table if exists block cascade;
drop table if exists content cascade;

create table "user"
(
    user_id bigint generated by default as identity,
    card_id bigint not null,
    login varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    primary key (user_id)
);

create table card
(
    card_id bigint generated by default as identity,
    block_id bigint not null,
    url varchar(255) not null,
    primary key (card_id)
);

create table block
(
    block_id bigint generated by default as identity,
    content_id bigint not null,
    name varchar(255) not null,
    content varchar(255) not null,
    primary key (block_id)
);

create table content
(
    content_id bigint generated by default as identity,
    name varchar(255) not null,
    description varchar(255) not null,
    primary key (content_id)
);

alter table if exists "user" add constraint fk_card_id foreign key (card_id) references card;
alter table if exists card add constraint fk_block_id foreign key (block_id) references block;
alter table if exists block add constraint fk_content_id foreign key (content_id) references content;